# Numby là thư viện giành cho việc sử lý các con số


## Các thư viện khác được xây dựng dựa trên Numpy

Viêt lên dựa trên ngôn ngữ C => Khi viết trển Python thì có kiểu dữ liệu "List" ( Danh sách ) thì ở Numpy ta có kiểu dữ liệu "Mảng" cho phép thực hiện các thao tác trên mảng

## Khai báo thư viện Numpy

In [16]:
import numpy as np # Khai báo thư viện với tên np

## Tạo mảng Numpy từ List Python

In [10]:
np.array([1, 2, 3, 4]) # Tạo mảng 1 , 2, 3, 4

array([1, 2, 3, 4])

In [14]:
np.array([1, 2, 3, 4.1, 5]) # Mảng chuyển về kiểu số thực từ thấp lên cao

array([1. , 2. , 3. , 4.1, 5. ])

In [16]:
np.array([1, 2, 3, 4.1, 5]).dtype # Float 64bit

dtype('float64')

In [22]:
np.array([1, 2, 3, 4.1, 5], dtype= 'int64') # Chuẩn hóa kiểu dữ liều về số nguyên 64 bit

array([1, 2, 3, 4, 5], dtype=int64)

In [24]:
a1 = np.array([1, 2, 3, 4, 5]) # Gán biến a1 với Mảng

In [26]:
type(a1) # Kiễu dữ liệu Mảng nd.array

numpy.ndarray

In [30]:
a2 = np.array([[1, 2, 3], # Khai báo mảng 2 chiều
             [4, 5, 6]])

In [32]:
type(a2)

numpy.ndarray

In [34]:
a2.shape # Xuất số cột và hàng của a2

(2, 3)

In [36]:
a2.ndim # Xuất số chiều của Mảng

2

In [38]:
a2.dtype # Xuất kiểu dữu liệu trong Mảng

dtype('int32')

In [40]:
a2.size # Trả lại số thành phần trong Mảng

6

## Tạo Mảng Numpy từ các hàm cho sẵn của Numpy

### zeros, ones, full, arange, linspace

In [55]:
np.zeros([2, 4], dtype='int') #  Xuất 2 cột 4 hàng số 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
np.ones([5, 3], dtype='int') # Xuất 2 cột và 3 hàng là số 1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
np.arange(0, 20, 2) # Tạo mảng từ 0 dến 20 bước nhảy là 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
np.full([3, 5], 6.9) # Tạo mảng 3 cột 5 dòng là 6.9

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [77]:
np.linspace(0,1, 5) # Tạo mảng từ 0 đến 1 bước nahry chia đều cho 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random

In [94]:
np.random.seed(0) # Giữ lại dãy số random trong Mảng
np.random.random([4,4]) # Tạo hàm 4 hàng 4 cột với giá trị từ 0 đến 1

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [102]:
np.random.normal(0, 1,(3,3)) # 0 là giá trị trung bình 1 là độ lệch chuẩn với mảng 3 hàng 3 cột

array([[-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252]])

In [110]:
np.random.randint(0, 10, (4, 5)) # Tảo bảng ngẫu nhiên nguyên dương từ 0 và không gồm 10

array([[4, 4, 8, 4, 3],
       [7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5],
       [0, 1, 2, 4, 2]])

In [115]:
np.random.rand(4,4) # Tjao ma trận ngẫu nhiên 4 cột 4 hàng

array([[0.50896896, 0.91672295, 0.92115761, 0.08311249],
       [0.27771856, 0.0093567 , 0.84234208, 0.64717414],
       [0.84138612, 0.26473016, 0.39782075, 0.55282148],
       [0.16494046, 0.36980809, 0.14644176, 0.56961841]])

### Tiếp cận Mảng Numpy và Cắt Mảng

#### Truy cập vào thành phân trong Mảng

In [22]:
x1 = np.random.randint(20, size = 6) # Tọa  mảng ngẫu nhiên từ 0 đến 20 gồm 6 thành phần

In [24]:
x1

array([19, 19,  6, 16, 18,  4])

Muốn tiếp cận vị trí số 3 trong Mảng

In [34]:
x1[4] # Truy cập thành phần thứ 5 trong Mảng

18

In [36]:
x1[0] # Truy cập thành phân đầu tiên trong Mảng

19

In [38]:
x1[-1] # Truy cập thành phần cuối cùng trong Mảng 

4

Giống với Mảng một chiều ta có thể truy cập vào phần từ đối với các ma trận đa chiều = INDEX

In [61]:
x2 = np.random.randint(10, size = (3, 4)) # Tạo mảng 2 chiều 3 x 4 gồm các số ngẫu nhiên từ 0 đến 310

In [63]:
x2

array([[0, 8, 4, 6],
       [1, 5, 8, 8],
       [9, 3, 4, 9]])

In [67]:
x2[1,2] # Vị trí cột 3 hàng 1

8

In [73]:
x2[2, 2] = 6 # Thay đổi gia trị của Mảng bằng Index hàng 3 cột 3 

In [75]:
x2

array([[0, 8, 4, 6],
       [1, 5, 8, 8],
       [9, 3, 6, 9]])

#### Cắt Numpy Array

`x[bắt dầu : kết thúc : bước nhảy]`

In [89]:
x1

array([19, 19,  6, 16, 18,  4])

In [84]:
x1[0:3] # Không bao gồm gia trị cuối

array([19, 19,  6])

In [87]:
x1[2:4]

array([ 6, 16])

In [95]:
x1[::2] # Căt các thành phần với index tăng mỗi 2 bước

array([19,  6, 18])

In [97]:
x2 # Đới với Mảng 3 x 4

array([[0, 8, 4, 6],
       [1, 5, 8, 8],
       [9, 3, 6, 9]])

In [105]:
x2[:2,:3] # Cắt mảng 2 cột và 3 hàng

array([[0, 8, 4],
       [1, 5, 8]])

In [107]:
x2[:,:2]

array([[0, 8],
       [1, 5],
       [9, 3]])

#### Thay đổi Ma trận và Transpose

In [110]:
grid = np.arange(1, 10)
grid.shape # Là Mảng 1 chiều

(9,)

In [128]:
x = grid.reshape((3,3))
x.shape # Chuyển đổi Mảng 1 chiều thành Mảng 3 x 3

(3, 3)

#### Transposes : Chuyển cột thành hàng

In [118]:
x2

array([[0, 8, 4, 6],
       [1, 5, 8, 8],
       [9, 3, 6, 9]])

In [122]:
x2.T # Chuyển cột thành hàng

array([[0, 1, 9],
       [8, 5, 3],
       [4, 8, 6],
       [6, 8, 9]])

#### Nối Numoy Array và Cắt Numpy thành phần nhỏ

In [137]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

In [141]:
np.concatenate((a, b)) # Nối 2 Mảng a, b với nhau

array([1, 2, 3, 3, 2, 1])

In [157]:
gird_1 = np.array(([1, 2, 3],
               [4, 5, 6]))

In [161]:
gird_1 # Mảng 2 x 3

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
np.concatenate((gird_1, gird)) # Nối với nhau theo chiều hàng axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [175]:
np.concatenate((gird_1, gird), axis = 1) # Nối với nhau theo cột axis = 1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [199]:
# vstack
x = np.array(([1, 2, 3]))
y = np.array(([1, 2, 3],
             [4, 5, 6]))

In [203]:
np.vstack((x, y)) # Gộp theo cột 

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [213]:
x3 = np.array(([2],
              [9])) # Nối theo chiều ngang
np.hstack((x3, y))

array([[2, 9, 7, 8],
       [9, 1, 3, 4]])

#### Chia nhỏ Mảng

In [238]:
x = np.array([1, 2, 3, 4 ,5 ,6 , 7, 8, 9, 10])

In [244]:
x1, x2, x3 = np.split(x, [3,5]) # Lưu mảng chia nhỏ lấy vị trí 4 và 6

In [242]:
x1 , x2, x3 

(array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10]))

#### Broadcasting and Vecto

Hiểu đơn giản là tạo bảng tương đương rồi thực hiện các phép Toán học dựa theo Mảng

In [250]:
a = np.arange(3)

In [252]:
a + 5 # Từ số 5 tạo mảng 3 phần tử gồm 3 số 5 rồi cộng cho mảng a

array([5, 6, 7])

In [258]:
b = np.ones((3, 3), dtype = 'int')

In [272]:
b + a # Nhân bản Mảng a bằng size với Mảng b rồi thực hành phép tính

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [274]:
b * a

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [290]:
c = np.arange(3).reshape((3, 1))
c # Ba hàng 1 cột

array([[0],
       [1],
       [2]])

In [292]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Tạo thành ma trận 3 nhân ba với c thì nhân 3 và a cũng nhân 3 lên

### Manipulating

#### Aggregation: Phép toán cho 1 Array

In [297]:
ll = [1, 2, 3]
list_n = np.array(ll)

In [299]:
list_n

array([1, 2, 3])

In [305]:
np.sum(list_n) # Tính toàn từ thư viện Numpy

6

In [307]:
sum(list_n) # Tính toán nhanh chóng hơn

6

In [309]:
# Tạo mảng lớn
d = np.random.random(1000)
d[:5]
d.shape

(1000,)

Numpy dùng phép toán nhanh hơn Python trong bảng đa chiều

In [318]:
np.mean(d) # Trung bình

0.503547102984419

In [320]:
np.max(d) # Gía trị lớn nhất

0.9979151723971315

In [322]:
np.min(d) # Gía trị nhỏ nhất

0.0013085300252044796

 ### Độ lệch chuẩn và Phương sai ( Xắc suất thống kê )

Độ lệch chuẩn: là kích thước độ phân tán của dữ liệu so vói giá trị mean
Phương sai: Từng điểm trong dữ liệu trừ đi giá trị trung bình rồi bình phương rồi tính giá trị trung bình của bình phương đó với nhau

In [331]:
dog_height = [600, 470, 170, 430, 300] # Tạo Mảng lưu trữ chiều cao của những con chó
e = np.array(dog_height)

In [349]:
np.std(e) # Tính độ lệch chuẩn

147.32277488562318

In [351]:
np.var(e) # Tính phương sai

21704.0

In [353]:
np.sqrt(np.var(e))

147.32277488562318

In [355]:
np.mean(e) # Tính trung bình

394.0

### Sắp xếp Mảng

In [371]:
arr = np.array([2, 5, 7, 9, 1])
np.sort(arr) # Sắp xếp măng tăng dần

array([1, 2, 5, 7, 9])

In [381]:
np.argsort(arr) # Trả về vị trí của Index trước khi xắp xếp

array([4, 0, 1, 2, 3], dtype=int64)

#### Xắp sếp mảng đa chiều

In [390]:
np.random.seed(42)
f = np.random.randint(0,10, size=(4, 6))

In [394]:
f

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [398]:
np.sort(f, axis=0) # Xắp xếp theo cột

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [402]:
np.sort(f, axis=1) # Sắp xếp theo hàng

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Đại số tuyến tính ( Nhân Ma Trận )

In [407]:
MarA = np.array(([1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]))

In [411]:
MarA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [413]:
MarB = np.array(([6, 5],
                [4, 3],
                [2, 1]))

Tích vô hướng giữa ma trận A và B là một ma trận 2 x 3

In [419]:
MarA.dot(MarB) # Tính tích vô hướng giữa Ma Trận A và B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [424]:
MarA @ MarB # Cũng được dùng để tính tích vô hướng

array([[20, 14],
       [56, 41],
       [92, 68]])

In [428]:
MarB.T @ MarA # Tích vô hướng của Ma trận B đổi chiều và Ma trận A

array([[36, 48, 60],
       [24, 33, 42]])

#### Ví dụ về Tích Vô Hướng

In [439]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))

In [443]:
import pandas as pd 
weekly_series = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed ","Thurs", "Fri"],
                                            columns = ["Almond Butter", "Peanut Butter","Cashew Butter"])

In [447]:
weekly_series # Tạo DâtFrame từ dư liệu thô Pandas

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [455]:
prices = np.array([10, 8 ,12]) # Tạo mảng chứa giá sản phẩm
prices.shape

(3,)

In [465]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index = ["Prices"], columns=["Almond Butter", "Peanut Butter","Cashew Butter"])

In [467]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [469]:
butter_prices.shape, weekly_series.shape

((1, 3), (5, 3))

In [471]:
total_prices = weekly_series @ butter_prices.T

In [473]:
weekly_series["Total_Prices"] = total_prices

In [475]:
weekly_series

Almond Butter  Peanut Butter  Cashew Butter  Total_Prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142